#!/bin/bash

chinit="./chinit"

$chinit echo  "Test start" >&2 || exit $(echo "Test failed 0" >&2 ; echo 1)

status=$($chinit bash -c 'exit 123; ls'; echo $?)
[[ $status == 123 ]] && echo 'Test ok' || exit $(echo "Test failed 1" >&2 ; echo 1)

UNIQ_TIME=3.56789

$chinit sudo sleep $UNIQ_TIME &

root_pid=$(echo $!)

sleep .2

pgrep -f $UNIQ_TIME > /dev/null

echo "Terminated message expected... :" >&2
kill -15 $root_pid || exit $(echo "Test failed 2" >&2 ; echo 1)

sleep .2

pgrep -f $UNIQ_TIME > /dev/null && exit $(echo "Test failed 3" >&2; echo 1) || echo 'Test ok'
ps aux | grep "sleep $UNIQ_TIME" | grep -v grep || true
pkill -f $UNIQ_TIME

$chinit --exec sudo sleep $UNIQ_TIME &

root_pid=$(echo $!)

sleep .2

pgrep -f $UNIQ_TIME > /dev/null

echo "Terminated message expected... :" >&2
kill -15 $root_pid || exit $(echo "Test failed 4" >&2 ; echo 1)

sleep .2

pgrep -f $UNIQ_TIME > /dev/null && echo 'Test ok' || exit $(echo "Test failed 5" >&2; echo 1)
