.TH CHINIT 1


.SH NAME
chinit - change init (run process in new pid namespace)


.SH SYNOPSYS
.B chinit
[\fIoptions\fR]
[\fIcommand\fR]


.SH DESCRIPTION
.B chinit
executes \fIcommand\fR in new pid namespace;
see
.BR  pid_namespace (7)
for more details.
Closing of created pid namespace is garanted
in cases of termination of execututed \fIcommand\fR
or any of auxiliary processes,
including initially launched one.
It is guaranteed by kernel
that all descendant processes will be destroyed.


.SH OPTIONS
.TP
.BR \-e ", " \-\-exec
Perform exec to given \fIcommand\fR in 'init' process of new namespace instead of vfork/exec pair;
see
.BR NOTES
for details.
.TP
.BR \-p ", " \-\-proc
Remount
.BR proc (5).
.TP
.BR \-h ", " \-\-help
Show short help and exit.


.SH EXIT STATUS
Normally
.B chinit
returns exit status of executed command.
.br
If any of auxiliary processes is killed by a signal,
returns the appropriate status (128 + WTERMSIG(status)).
.br
If internal error occurred, returns EXIT_FAILURE.


.SH NOTES
.B chinit
implementation scheme:
    root process
        with \-\-proc:
            unshare(CLONE_NEWPID|CLONE_NEWNS) (slower!)
        else
            unshare(CLONE_NEWPID)
        fork -> waitpid for child process
        with \-\-proc:
            remount /proc/
        drop privileges
    child process ('init' for new pid namespace):
        set prctl(PR_SET_PDEATHSIG, SIGKILL)
        with --exec option:
            execvp(\fIcommand\fR) (unsafe for some commands)
        else:
            vfork -> waitpid for child process
            execvp(\fIcommand\fR)

According to
.BR prctl (2),
PR_SET_PDEATHSIG will be cleared:
  * for the child of a fork
  * when executing a set-user-ID or set-group-ID binary
.br
Since it is difficult to determine if the parent will reset this flag, then an additional fork used by default.
.br
If \fIcommand\fR does not do anything of the above, is is possible to use
.BR \-\-exec
flag and save one fork.


.SH BUGS
The best way to report a bug is to create an issue on https://github.com/romanoved/chinit/issues .


.SH AUTHOR
Evgenii D. Romanov <romanoved@yandex.ru>


.SH SEE ALSO
.BR prctl (2),
.BR unshare (2),
.BR vfork (2),
.BR waitpid (2),
.BR exec (3),
.BR proc (5),
.BR pid_namespace (7)
